### PR TITLE
Try out PMIP request

### PR DESCRIPTION
**Pull request by jbusecke**

### CODE REVIEW

**Comment by jbusecke** [comment]
cc @CommonClimate

**Comment by jbusecke** [comment]
Next action items: 
- Debug the issue with time (registrar logs)
- Add some more instance ids (see #10)

**Comment by cisaacstern** [comment]
@jbusecke lmk if I can advise here! Happy to help where I can.

**Comment by jbusecke** [comment]
I am pretty sure I know what the problem here is:
In order to estimate the chunksize we construct a pandas datetime array, which in this instance is extremely long (2000years monthly, which pandas cannot currently handle @CommonClimate might have the link to the pandas issue)

I am sure I could find a paleo (PMIP) specific hacky solution but I wonder if all of this will "go away" as part of the broader beam refactor. Relying on an estimate of time steps using dates is ultimately a crutch. Pgf should be able to inspect the size of the cached files and then determine the chunksize without ever needing to know about the actual time values.

Having this be part of pgf and not this (growing) recipe would make things a lot easier.

**Comment by CommonClimate** [comment]
Yes, I believe the issue is related to the minimum timestamp allowable in pandas under a datetime64[ns] encoding: https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.min.html

PMIP runs will all violate this requirement; in fact, I am surprised you haven't experienced the [max limitation ](https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.max.html) with CMIP6 projections into the year 2300. Perhaps you haven't tried the recipe on those? 

As I was telling @jbusecke , we are working with Quansight to broaden `pandas`' time representation, which may help with this but will realistically take a few more months. An easy fix is to pass `decode_times = False`, but you will lose access to `datetime` functionalities, and therefore pandas.  If you have a solution that can get chunks without needing to know the time, that would be the most robust.

**Comment by jbusecke** [comment]
> PMIP runs will all violate this requirement; in fact, I am surprised you haven't experienced the max limitation with CMIP6 projections into the year 2300. Perhaps you haven't tried the recipe on those?

Yep you are right here, the current datasets are not covering the scenarios yet.
This is however a broader motivation to change the way we determine the number of timesteps in each instance. 

Let me spend a bit of time to come up with a more rudimentary way of doing this, which might just solve this problem for us. Ill report back

**Comment by jbusecke** [comment]
I am making some progress over in #16, and will close this one

**Pull request closed without merging**
