### PR TITLE
Add PMIP runs to recipe

### PR DESCRIPTION
**Pull request by jbusecke**
This PR superseeds #14, and is already rebased on #15. For previous discussions please refer to https://github.com/pangeo-forge/cmip6-feedstock/pull/14

It passed locally for me, lets see if we can actually build the dataset.

### CODE REVIEW

**Comment by jbusecke** [comment]
@CommonClimate could you check the output, and see if these look ok to you? Ill run the others now.

**Comment by jbusecke** [comment]
The logs say: 
```
2022-07-01T14:45:33.649718+00:00 (INFO)

Submitted for execution: Job prefect-job-fad0a939

2022-07-01T14:57:08.484788+00:00 (INFO)

Rescheduled by a Lazarus process. This is attempt 1.

2022-07-01T14:57:11.170213+00:00 (INFO)

Submitted for execution: Job prefect-job-73b21ee5

2022-07-01T15:09:07.186314+00:00 (INFO)

Rescheduled by a Lazarus process. This is attempt 2.

2022-07-01T15:09:10.845308+00:00 (INFO)

Submitted for execution: Job prefect-job-9768abae

2022-07-01T15:21:16.937544+00:00 (INFO)

Rescheduled by a Lazarus process. This is attempt 3.

2022-07-01T15:21:18.624253+00:00 (INFO)

Submitted for execution: Job prefect-job-6c752e03

2022-07-01T15:32:22.22285+00:00 (ERROR)

A Lazarus process attempted to reschedule this run 3 times without success. Marking as failed.
```

I am not at all sure what this means. will retry one of the jobs.

**Comment by jbusecke** [comment]
Same issue with the Lazarus process. I am going to wait for some input from @cisaacstern side here.

**Comment by cisaacstern** [comment]
Thanks for the ping Julius. I admittedly don't know what this is off the top of my head but I'll look into it.

**Comment by jbusecke** [comment]
Thanks Charles.

**Comment by CommonClimate** [comment]
The code snippet above works like a charm! I'm able to load and plot the data without a hitch, in just a couple of seconds:
MPI_ESM1 2_zarr_mean

**Comment by jbusecke** [comment]
Seems like the 2k simulation is (possibly temporarily) unavailable. I will try to run one of the others one more time.

**Comment by jbusecke** [comment]
From the logs it seems like the 'Lazarus' thing might have just been a temporary issue.

**Comment by cisaacstern** [comment]
Apologies for the delayed response here. Please let me know if/how I can be of assistance at this point.

**Comment by CommonClimate** [comment]
adding @jordanplanders to this conversation, as she will be taking this over for a bit

**Comment by CommonClimate** [comment]
Well @cisaacstern the question remains the same: what do we have have to do at this point? Go through the checklist and complete the review? Sorry we are new to this process, so we need a bit of hand-holding.

**Comment by cisaacstern** [comment]
Yes, someone with knowledge of the data opening it and answering the checklist provided in https://github.com/pangeo-forge/cmip6-feedstock/pull/16#issuecomment-1178001348 would be helpful. Beyond that, I will defer to @jbusecke who has been following this PR much more closely than me.

**Comment by jbusecke** [comment]
Ughhh this does not seem a great day for ESGF. I am seeing a bunch of 503s and the one datasets that generates a recipe then fails with another server error:
```
FileNotFoundError(url) from exc FileNotFoundError: http://esgf3.dkrz.de/thredds/fileServer/cmip6/PMIP/MPI-M/MPI-ESM1-2-LR/past2k/r1i1p1f1/Amon/tas/gn/v20210714/tas_Amon_MPI-ESM1-2-LR_past2k_r1i1p1f1_gn_700101-702012.nc
```

Ill try to push to this some time later and see if we have more luck?

**Comment by jordanplanders** [comment]
@jbusecke I took the gn.dummy version for a spin and it worked fine, except it only returned the first two chunks.  Running:
```
dataset_public_url = 'https://ncsa.osn.xsede.org/Pangeo/pangeo-forge-test/prod/recipe-run-984/pangeo-forge/cmip6-feedstock/CMIP6.PMIP.MPI-M.MPI-ESM1-2-LR.past2k.r1i1p1f1.Amon.tas.gn.v20210714.zarr'
mapper = fsspec.get_mapper(dataset_public_url)

ds_tmp = xr.open_zarr(mapper,  consolidated=True, decode_times=False)
ds_tmp
```

returned:
```
FileNotFoundError: https://ncsa.osn.xsede.org/Pangeo/pangeo-forge-test/prod/recipe-run-984/pangeo-forge/cmip6-feedstock/CMIP6.PMIP.MPI-M.MPI-ESM1-2-LR.past2k.r1i1p1f1.Amon.tas.gn.v20210714.zarr/.zmetadata
```

It's probably user error (pardon), but maybe you can give me a nudge in the right direction?

**Comment by jbusecke** [comment]
First of all, hi Jordan! Its been a while since we were working on problem-sets for oceanography? Very good to see you here!

> It's probably user error (pardon), but maybe you can give me a nudge in the right direction?

I actually think this is not on you. I think this particular run failed (for reasons I need to investigate). I just tried to open it and I think there is only a folder with nothing in it. 

I am looking into this with @cisaacstern right now, and we will report back!

**Comment by jordanplanders** [comment]
Hi!! So it has!  

I think I'm still pretty fuzzy about the backend of pangeo-forge, but I grabbed code from [the cmip6-feedstock recipe.py](https://github.com/pangeo-forge/cmip6-feedstock/blob/6df9f298fbde1f0af3b35ac03852b68de5f91eea/feedstock/recipe.py) and tried it on `CMIP6.DAMIP.NOAA-GFDL.GFDL-ESM4.hist-aer.r1i1p1f1.Amon.pr.gr1.v20180701` and it identified all parts of the dataset correctly (when I compared it to the web ui), but when I tried it on `CMIP6.PMIP.MPI-M.MPI-ESM1-2-LR.past2k.r1i1p1f1.Amon.tas.gn.v20210714`, it only returned 10 of 93 ([Gist here](https://gist.github.com/jordanplanders/9191bdef8498e00ee86af936332a2ae8)). It's not obvious to me why that would cause it to fail per se, but I can imagine there might be a check that fails if the dataset end date doesn't correspond with the last date of the last block? 

I wrote a [little bit of code](https://gist.github.com/jordanplanders/227ca18c773236c77fcd55ac3ee8c55b) to pull together a url list for past2k, and expected it to break for the GFDL data (which is to say: I expected there was something weird about past2k that was fouling things up), but it didn't (I changed the stem url string appropriately). 

 Maybe something in all of this will help root out the issue...

**Comment by jbusecke** [comment]
Ah that is helpful, thanks.

This bit is interesting and warrants some more digging:
> it only returned 10 of 93

I assume that is file urls in this case? If there is a discrepancy between the web search and the API based search, that might have to be raised upstream with the ESGF folks.

I will merge this one now, and see if the issue you describe persists. 
Ill investigate a bit further next week. 

Overall @cisaacstern and I have discussed to split out the PMIP datasets into a separate feedstock (https://github.com/pangeo-forge/staged-recipes/pull/162) to keep things a bit more organized. None of that should for now make a difference with this issue, but it will enable us to treat your request more in isolation. 
Once we have that feedstock merged we can move dissussions over there.

**Comment by jbusecke** [comment]
I think I found the bug, actually. 
I previously did not set the limit on the request parameters (and I believe it defaults to 10! results or files in this case). 
I just changed it to 500 [here](https://github.com/pangeo-forge/cmip6-feedstock/blob/63f544892df0f6c7c61bf372bfd52366cd885aa7/feedstock/recipe.py#L46) and locally get the correct number of 93 files!
Lets see if this fixes that issue.

**Comment by jbusecke** [comment]
So I was able to do this:
```python
import fsspec
import xarray as xr

dataset_public_url = 'https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/cmip6-feedstock/CMIP6.PMIP.MPI-M.MPI-ESM1-2-LR.past2k.r1i1p1f1.Amon.tas.gn.v20210714.zarr'
mapper = fsspec.get_mapper(dataset_public_url)

ds = xr.open_zarr(mapper,  consolidated=True, decode_times=False)
ds
```
and get 
image

Does that look about right to you?

**Comment by jordanplanders** [comment]
Yes! Thank you!

**Comment by CommonClimate** [comment]
Looks dandy, thank you. I support moving this to  a different recipe if it simplifies your workflow - just let us know where to follow this discussion.

**Comment by jbusecke** [comment]
We are still working out some kinks. I will definitely notify you here once the feedstock is generated. Thanks for the patience!

**Pull request merged**
